/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import Database.Connect;
import DataAccess.Table;
import java.awt.event.KeyEvent;

public class JFrameAddAccount extends javax.swing.JFrame {

    public static Connection conn = Connect.getConnect();
    public static PreparedStatement pst = null;
    public static CallableStatement cst = null;
    public static ResultSet rs = null;
            
    public JFrameAddAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabeRegisterFullName = new javax.swing.JLabel();
        jLabelResgisterPassword = new javax.swing.JLabel();
        jLabelRegisterUserName = new javax.swing.JLabel();
        jLabelRegisterRetypePassword = new javax.swing.JLabel();
        jButtonRegister = new javax.swing.JButton();
        jButtonCancelAddAccount = new javax.swing.JButton();
        jTextFieldRegisterFullName = new javax.swing.JTextField();
        jTextFieldRegisterUserName = new javax.swing.JTextField();
        jPasswordResgisterPassword = new javax.swing.JPasswordField();
        jPasswordRegisterRetypePassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(206, 59));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng ký tài khoản mới");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        jLabeRegisterFullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeRegisterFullName.setText("Họ và tên:");

        jLabelResgisterPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelResgisterPassword.setText("Mật khẩu:");

        jLabelRegisterUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRegisterUserName.setText("Tên đăng nhập:");

        jLabelRegisterRetypePassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRegisterRetypePassword.setText("Nhập lại:");

        jButtonRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRegister.setText("Đăng ký");
        jButtonRegister.setPreferredSize(new java.awt.Dimension(87, 25));
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jButtonRegister.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonRegisterKeyPressed(evt);
            }
        });

        jButtonCancelAddAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelAddAccount.setText("Quay lại");
        jButtonCancelAddAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelAddAccountActionPerformed(evt);
            }
        });
        jButtonCancelAddAccount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCancelAddAccountKeyPressed(evt);
            }
        });

        jTextFieldRegisterFullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldRegisterFullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRegisterFullNameKeyPressed(evt);
            }
        });

        jTextFieldRegisterUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldRegisterUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRegisterUserNameActionPerformed(evt);
            }
        });

        jPasswordResgisterPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPasswordRegisterRetypePassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPasswordRegisterRetypePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordRegisterRetypePasswordActionPerformed(evt);
            }
        });
        jPasswordRegisterRetypePassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordRegisterRetypePasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelResgisterPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRegisterUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRegisterRetypePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabeRegisterFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPasswordResgisterPassword, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRegisterUserName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordRegisterRetypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRegisterFullName, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRegisterUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegisterUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordResgisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelResgisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordRegisterRetypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRegisterRetypePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeRegisterFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRegisterFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelAddAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelAddAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelAddAccountActionPerformed
        // Thoát khỏi đăng ký
        dispose();
    }//GEN-LAST:event_jButtonCancelAddAccountActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        // BUTTION ĐĂNG KÝ TÀI KHOẢN.
        jButtonCancelAddAccount.setEnabled(true);
        // Kiểm tra Tài khoản có tồn tại chưa:
        boolean isExist = false;
        try {
            pst = conn.prepareStatement("SELECT * FROM quanlyquancafethucan.taikhoandangnhap WHERE UserName = ?");
            pst.setString(1, jTextFieldRegisterUserName.getText());
            rs = pst.executeQuery();
            if(rs.next()) {
                JOptionPane.showMessageDialog(null, "Tài khoản này hiện đã tồn tại, vui lòng chọn một tên khác!", "Tài khoản đã tồn tại!", 2);
                isExist = true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "JFrameAddAccount", 2);
        }
        // Kiểm tra có trường nào chưa điền không:
        if(jTextFieldRegisterFullName.getText().length() == 0 || jTextFieldRegisterUserName.getText().length() == 0 || jPasswordResgisterPassword.getText().length() == 0 || jPasswordRegisterRetypePassword.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin", "Nhập thiếu thông tin", 2);
        }
        // Kiểm tra mật khẩu có trùng khớp không:
        else if(!(jPasswordResgisterPassword.getText().equals(jPasswordRegisterRetypePassword.getText()))){
            JOptionPane.showMessageDialog(null, "Bạn phải nhập mật khẩu trùng khớp nhau", "Thông báo", 2);
        }
        else if(isExist == false){
            try {
                cst = conn.prepareCall("{CALL DangKyTaiKhoan(?, ?, ?)}");
                cst.setString(1, jTextFieldRegisterUserName.getText());
                cst.setString(2, jPasswordResgisterPassword.getText());
                cst.setString(3, jTextFieldRegisterFullName.getText());
                cst.executeQuery();
                JOptionPane.showMessageDialog(null, "Đăng ký tài khoản thành công!", "Thành công.", 1);
                Table.LoadDataTable("SELECT ID AS 'STT', UserName AS 'Tên đăng nhập', FullName AS 'Họ và tên' FROM quanlyquancafethucan.taikhoandangnhap ORDER BY ID ASC", JFrameMain.Admin.jTableAccount);
                jTextFieldRegisterFullName.setText(null);
                jTextFieldRegisterUserName.setText(null);
                jPasswordResgisterPassword.setText(null);
                jPasswordRegisterRetypePassword.setText(null);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e, "ErrorAtJFrameAddAccount", 2);
            }
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed
    
    private void jTextFieldRegisterUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRegisterUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRegisterUserNameActionPerformed

    private void jPasswordRegisterRetypePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordRegisterRetypePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordRegisterRetypePasswordActionPerformed

    private void jPasswordRegisterRetypePasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordRegisterRetypePasswordKeyPressed
        // Nhấn phím ENTER == Đăng ký:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonRegister.doClick();
        }
    }//GEN-LAST:event_jPasswordRegisterRetypePasswordKeyPressed

    private void jButtonCancelAddAccountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCancelAddAccountKeyPressed
        // Nhấn ENTER Nút Thoát == Nhấn buttion
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonCancelAddAccount.doClick();
        }
    }//GEN-LAST:event_jButtonCancelAddAccountKeyPressed

    private void jTextFieldRegisterFullNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRegisterFullNameKeyPressed
        // ENTER == ĐĂNG KÝ:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonRegister.doClick();
        }
    }//GEN-LAST:event_jTextFieldRegisterFullNameKeyPressed

    private void jButtonRegisterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonRegisterKeyPressed
        // ENTER == ĐĂNG KÝ:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonRegister.doClick();
        }
    }//GEN-LAST:event_jButtonRegisterKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAddAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAddAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelAddAccount;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabeRegisterFullName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRegisterRetypePassword;
    private javax.swing.JLabel jLabelRegisterUserName;
    private javax.swing.JLabel jLabelResgisterPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordRegisterRetypePassword;
    private javax.swing.JPasswordField jPasswordResgisterPassword;
    private javax.swing.JTextField jTextFieldRegisterFullName;
    private javax.swing.JTextField jTextFieldRegisterUserName;
    // End of variables declaration//GEN-END:variables
}
