/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import Database.Connect;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import DataAccess.Table;

public class JFrameEditTableFood extends javax.swing.JFrame {

    public static Connection conn = Connect.getConnect();
    public static PreparedStatement pst = null;
    public static CallableStatement cst = null;
    public static ResultSet rs = null;
            
    public JFrameEditTableFood() {
        initComponents();
        jComboBoxEditTableStatus.addItem("Trống");
        jComboBoxEditTableStatus.addItem("Có người");
        
        jTextFieldEditTableFoodName.setText(JFrameMain.Admin.jTextFieldTableFoodName.getText());
        jSpinnerEditTableFoodID.setValue((int) JFrameMain.Admin.jSpinnerTableFoodID.getValue());
        jComboBoxEditTableStatus.setSelectedItem(JFrameMain.Admin.jComboBoxTableFoodStatus.getSelectedItem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabeEditTableFoodName = new javax.swing.JLabel();
        jLabeEditTableFoodStatus = new javax.swing.JLabel();
        jButtonEditTableFood = new javax.swing.JButton();
        jButtonCancelEditTableFood = new javax.swing.JButton();
        jTextFieldEditTableFoodName = new javax.swing.JTextField();
        jComboBoxEditTableStatus = new javax.swing.JComboBox();
        jLabeEditTableFoodID = new javax.swing.JLabel();
        jSpinnerEditTableFoodID = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sửa Thông Tin Bàn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jLabeEditTableFoodName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeEditTableFoodName.setText("Tên bàn:");

        jLabeEditTableFoodStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeEditTableFoodStatus.setText("Trạng thái");

        jButtonEditTableFood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditTableFood.setText("Lưu");
        jButtonEditTableFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditTableFoodActionPerformed(evt);
            }
        });
        jButtonEditTableFood.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonEditTableFoodKeyPressed(evt);
            }
        });

        jButtonCancelEditTableFood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelEditTableFood.setText("Quay lại");
        jButtonCancelEditTableFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelEditTableFoodActionPerformed(evt);
            }
        });
        jButtonCancelEditTableFood.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCancelEditTableFoodKeyPressed(evt);
            }
        });

        jTextFieldEditTableFoodName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEditTableFoodName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEditTableFoodNameKeyPressed(evt);
            }
        });

        jComboBoxEditTableStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabeEditTableFoodID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeEditTableFoodID.setText("Mã bàn:");

        jSpinnerEditTableFoodID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinnerEditTableFoodID.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabeEditTableFoodName, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jLabeEditTableFoodID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabeEditTableFoodStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEditTableFoodName)
                            .addComponent(jComboBoxEditTableStatus, 0, 190, Short.MAX_VALUE)
                            .addComponent(jSpinnerEditTableFoodID)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButtonEditTableFood, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelEditTableFood, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabeEditTableFoodName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldEditTableFoodName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeEditTableFoodID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerEditTableFoodID, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxEditTableStatus)
                    .addComponent(jLabeEditTableFoodStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditTableFood)
                    .addComponent(jButtonCancelEditTableFood))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelEditTableFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelEditTableFoodActionPerformed
        // QUAY LẠI
        dispose();
    }//GEN-LAST:event_jButtonCancelEditTableFoodActionPerformed

    private void jButtonEditTableFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditTableFoodActionPerformed
        // CHỈNH SỬA MỘT DÒNG TRONG THÔNG TIN BÀN ĂN:
        try {
            pst = conn.prepareCall("CALL CapNhatBanPhucVu (?, ?, ?)");
            pst.setInt(1, (int) jSpinnerEditTableFoodID.getValue());
            pst.setString(2, jTextFieldEditTableFoodName.getText());
            pst.setString(3, jComboBoxEditTableStatus.getSelectedItem().toString());
            pst.executeQuery();
            Table.LoadDataTable("SELECT ID AS 'Mã bàn', TenBan AS 'Tên Bàn', TrangThai AS 'Trạng Thái' FROM quanlyquancafethucan.BanPhucVu ORDER BY ID ASC", JFrameMain.Admin.jTableTableFood);
            JFrameLogin.MainGUI.resetTable();
            JFrameLogin.MainGUI.addTableButton();
            JOptionPane.showMessageDialog(null, "Chỉnh sửa thông tin bàn thành công!", "Sửa thông tin bàn.", 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "JFrameEditTableFood", 1);
        }
    }//GEN-LAST:event_jButtonEditTableFoodActionPerformed
    
    private void jButtonCancelEditTableFoodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCancelEditTableFoodKeyPressed
        // Nhấn ENTER Nút Thoát == Nhấn buttion
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonCancelEditTableFood.doClick();
        }
    }//GEN-LAST:event_jButtonCancelEditTableFoodKeyPressed

    private void jButtonEditTableFoodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonEditTableFoodKeyPressed
        // NHẤN ENTER == CLICK:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonEditTableFood.doClick();
        }
    }//GEN-LAST:event_jButtonEditTableFoodKeyPressed

    private void jTextFieldEditTableFoodNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEditTableFoodNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonEditTableFood.doClick();
        }
    }//GEN-LAST:event_jTextFieldEditTableFoodNameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEditTableFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEditTableFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEditTableFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEditTableFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEditTableFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelEditTableFood;
    private javax.swing.JButton jButtonEditTableFood;
    private javax.swing.JComboBox jComboBoxEditTableStatus;
    private javax.swing.JLabel jLabeEditTableFoodID;
    private javax.swing.JLabel jLabeEditTableFoodName;
    private javax.swing.JLabel jLabeEditTableFoodStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerEditTableFoodID;
    private javax.swing.JTextField jTextFieldEditTableFoodName;
    // End of variables declaration//GEN-END:variables
}
