/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataAccess.ComboBox;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import Database.Connect;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import DataAccess.Table;

public class JFrameAddTableFood extends javax.swing.JFrame {

    public static Connection conn = Connect.getConnect();
    public static PreparedStatement pst = null;
    public static CallableStatement cst = null;
    public static ResultSet rs = null;
            
    public JFrameAddTableFood() {
        initComponents();
        jComboBoxAddTableStatus.addItem("Trống");
        jComboBoxAddTableStatus.addItem("Có người");
        jTextFieldAddTableFoodName.setText("Bàn ");
        jSpinnerAddTableFoodID.setValue(JFrameMain.countTable + 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabeAddTableFoodName = new javax.swing.JLabel();
        jLabeAddTableFoodStatus = new javax.swing.JLabel();
        jButtonAddTableFood = new javax.swing.JButton();
        jButtonCancelAddTableFood = new javax.swing.JButton();
        jTextFieldAddTableFoodName = new javax.swing.JTextField();
        jComboBoxAddTableStatus = new javax.swing.JComboBox();
        jLabeAddTableFoodID = new javax.swing.JLabel();
        jSpinnerAddTableFoodID = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm Bàn Ăn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jLabeAddTableFoodName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeAddTableFoodName.setText("Tên bàn:");

        jLabeAddTableFoodStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeAddTableFoodStatus.setText("Trạng thái");

        jButtonAddTableFood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddTableFood.setText("Thêm");
        jButtonAddTableFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTableFoodActionPerformed(evt);
            }
        });
        jButtonAddTableFood.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAddTableFoodKeyPressed(evt);
            }
        });

        jButtonCancelAddTableFood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelAddTableFood.setText("Quay lại");
        jButtonCancelAddTableFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelAddTableFoodActionPerformed(evt);
            }
        });
        jButtonCancelAddTableFood.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCancelAddTableFoodKeyPressed(evt);
            }
        });

        jTextFieldAddTableFoodName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAddTableFoodName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAddTableFoodNameKeyPressed(evt);
            }
        });

        jComboBoxAddTableStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabeAddTableFoodID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeAddTableFoodID.setText("Mã bàn:");

        jSpinnerAddTableFoodID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinnerAddTableFoodID.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabeAddTableFoodName, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jLabeAddTableFoodID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeAddTableFoodStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldAddTableFoodName)
                    .addComponent(jComboBoxAddTableStatus, 0, 190, Short.MAX_VALUE)
                    .addComponent(jSpinnerAddTableFoodID))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jButtonAddTableFood, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelAddTableFood, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabeAddTableFoodName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldAddTableFoodName))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabeAddTableFoodID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerAddTableFoodID, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxAddTableStatus)
                    .addComponent(jLabeAddTableFoodStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddTableFood, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelAddTableFood, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelAddTableFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelAddTableFoodActionPerformed
        // QUAY LẠI
        dispose();
    }//GEN-LAST:event_jButtonCancelAddTableFoodActionPerformed

    private void jButtonAddTableFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTableFoodActionPerformed
        // Kiểm tra bàn đã tồn tại chưa:
        boolean isExist = false;
        try {
            pst = conn.prepareStatement("SELECT * FROM quanlyquancafethucan.banphucvu WHERE TenBan = ?");
            pst.setString(1, jTextFieldAddTableFoodName.getText());
            rs = pst.executeQuery();
            if(rs.next()) {
                JOptionPane.showMessageDialog(null, "Bàn này hiện đã tồn tại!", "Bàn tồn tại.", 2);
                isExist = true;     // Đã tồn tại.
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "JFrameAddTableFood.", 2);
        }
        // Nếu chưa thì thực hiện thêm bàn vào:
        if(JFrameMain.countTable == 24) {
            JOptionPane.showMessageDialog(null, "Số bàn tối đa cho phép là 24!", "Vượt quá số lượng.", 1);
        }
        else if(isExist == false) {
            try {
                cst = conn.prepareCall("{CALL ThemBan(? , ? , ?)}");
                cst.setInt(1, (int) jSpinnerAddTableFoodID.getValue());         //ID
                cst.setString(2, jTextFieldAddTableFoodName.getText());         // Tên Bàn
                cst.setString(3, jComboBoxAddTableStatus.getSelectedItem().toString()); // Trạng thái
                cst.executeQuery();
                Table.LoadDataTable("SELECT ID AS 'Mã', TenBan AS 'Tên Bàn', TrangThai AS 'Trạng Thái' FROM quanlyquancafethucan.BanPhucVu ORDER BY ID ASC", JFrameMain.Admin.jTableTableFood);
                JOptionPane.showMessageDialog(null, "Đã thêm " + jTextFieldAddTableFoodName.getText(), "Thêm bàn.", 1);
                JFrameLogin.MainGUI.resetTable();
                JFrameLogin.MainGUI.addTableButton();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Mã Bàn đã tồn tại rồi!", "ErrorAtJFrameAddTableFood", 1);
            }
        }
        JFrameLogin.MainGUI.jComboBoxChangeTable.removeAllItems();
        ComboBox.LoadDataComboBox("SELECT * FROM banphucvu", JFrameLogin.MainGUI.jComboBoxChangeTable, "TenBan");
    }//GEN-LAST:event_jButtonAddTableFoodActionPerformed
    
    private void jButtonCancelAddTableFoodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCancelAddTableFoodKeyPressed
        // Nhấn ENTER Nút Thoát == Nhấn buttion
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonCancelAddTableFood.doClick();
        }
    }//GEN-LAST:event_jButtonCancelAddTableFoodKeyPressed

    private void jButtonAddTableFoodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAddTableFoodKeyPressed
        // NHẤN ENTER == CLICK:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonAddTableFood.doClick();
        }
    }//GEN-LAST:event_jButtonAddTableFoodKeyPressed

    private void jTextFieldAddTableFoodNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAddTableFoodNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonAddTableFood.doClick();
        }
    }//GEN-LAST:event_jTextFieldAddTableFoodNameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAddTableFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAddTableFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAddTableFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAddTableFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAddTableFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddTableFood;
    private javax.swing.JButton jButtonCancelAddTableFood;
    private javax.swing.JComboBox jComboBoxAddTableStatus;
    private javax.swing.JLabel jLabeAddTableFoodID;
    private javax.swing.JLabel jLabeAddTableFoodName;
    private javax.swing.JLabel jLabeAddTableFoodStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerAddTableFoodID;
    private javax.swing.JTextField jTextFieldAddTableFoodName;
    // End of variables declaration//GEN-END:variables
}
