/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import Database.Connect;
import java.awt.event.KeyEvent;
import DataAccess.ComboBox;
import javax.swing.JOptionPane;
import DataAccess.Table;

public class JFrameEditMenu extends javax.swing.JFrame {

    public static Connection conn = Connect.getConnect();
    public static PreparedStatement pst = null;
    public static CallableStatement cst = null;
    public static ResultSet rs = null;
            
    public JFrameEditMenu() {
        initComponents();
        ComboBox.LoadDataComboBox("SELECT * FROM quanlyquancafethucan.PhanLoaiMenu", jComboBoxEditMennuCategory, "Ten");
        jTextFieldEditMenuFoodName.setText(JFrameMain.Admin.jTextFieldMenuFoodName.getText());
        jComboBoxEditMennuCategory.setSelectedItem(JFrameMain.Admin.jComboBoxMenuFoodCategory.getSelectedItem().toString());
        jTextFieldEditMenuPrice.setValue(JFrameMain.Admin.jSpinnerMenuPrice.getValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabeRegisterFullName = new javax.swing.JLabel();
        jLabelResgisterPassword = new javax.swing.JLabel();
        jLabelRegisterUserName = new javax.swing.JLabel();
        jButtonEditMenu = new javax.swing.JButton();
        jButtonCancelEditMenu = new javax.swing.JButton();
        jTextFieldEditMenuFoodName = new javax.swing.JTextField();
        jTextFieldEditMenuPrice = new javax.swing.JSpinner();
        jComboBoxEditMennuCategory = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chỉnh sửa món trong Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jLabeRegisterFullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeRegisterFullName.setText("Tên món:");

        jLabelResgisterPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelResgisterPassword.setText("Giá:");

        jLabelRegisterUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRegisterUserName.setText("Phân loại:");

        jButtonEditMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditMenu.setText("Lưu");
        jButtonEditMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditMenuActionPerformed(evt);
            }
        });
        jButtonEditMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonEditMenuKeyPressed(evt);
            }
        });

        jButtonCancelEditMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelEditMenu.setText("Quay lại");
        jButtonCancelEditMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelEditMenuActionPerformed(evt);
            }
        });
        jButtonCancelEditMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCancelEditMenuKeyPressed(evt);
            }
        });

        jTextFieldEditMenuFoodName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEditMenuFoodName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEditMenuFoodNameActionPerformed(evt);
            }
        });
        jTextFieldEditMenuFoodName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEditMenuFoodNameKeyPressed(evt);
            }
        });

        jTextFieldEditMenuPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEditMenuPrice.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1000.0d)));

        jComboBoxEditMennuCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelResgisterPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRegisterUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jLabeRegisterFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextFieldEditMenuFoodName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxEditMennuCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldEditMenuPrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButtonEditMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelEditMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeRegisterFullName)
                    .addComponent(jTextFieldEditMenuFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegisterUserName)
                    .addComponent(jComboBoxEditMennuCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldEditMenuPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabelResgisterPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditMenu)
                    .addComponent(jButtonCancelEditMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelEditMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelEditMenuActionPerformed
        // QUAY LẠI
        dispose();
    }//GEN-LAST:event_jButtonCancelEditMenuActionPerformed

    private void jButtonEditMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditMenuActionPerformed
        // BUTTION Đăng ký tài khoản đăng nhập mới.
        try {
            cst = conn.prepareCall("{CALL CapNhatMenu(? , ? , ? , ? , ?)}");
            cst.setInt(1, JFrameMain.Admin.IDMenu); // ID món
            // ID Phân loại 1. Nước uống || 2. Thức ăn || 3. Khác:
            if(jComboBoxEditMennuCategory.getSelectedItem().toString().equals("Nước uống")){
                cst.setInt(2, 1);
            }
            else if(jComboBoxEditMennuCategory.getSelectedItem().toString().equals("Thức ăn")){
                cst.setInt(2, 2);
            }
            else if(jComboBoxEditMennuCategory.getSelectedItem().toString().equals("Khác")){
                cst.setInt(2, 3);
            }
            cst.setString(3, jTextFieldEditMenuFoodName.getText()); // Tên món
            cst.setString(4, jComboBoxEditMennuCategory.getSelectedItem().toString());  // Phân loại
            cst.setDouble(5, (double) jTextFieldEditMenuPrice.getValue());  // Giá bán
            cst.executeQuery();
            JOptionPane.showMessageDialog(null, "Đã chỉnh sửa thành công!", "Chỉnh sửa.", 1);
            Table.LoadDataTable("SELECT ID AS 'ID', TenMon AS 'Tên món', PhanLoai AS 'Phân loại', Gia AS 'Giá bán' FROM quanlyquancafethucan.menu ORDER BY ID ASC", JFrameMain.Admin.jTableMenu);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "JFrameEditMenu", 2);
        }
    }//GEN-LAST:event_jButtonEditMenuActionPerformed
    
    private void jButtonCancelEditMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCancelEditMenuKeyPressed
        // Nhấn ENTER Nút Thoát == Nhấn buttion
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonCancelEditMenu.doClick();
        }
    }//GEN-LAST:event_jButtonCancelEditMenuKeyPressed

    private void jButtonEditMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonEditMenuKeyPressed
        // NHẤN ENTER == SỬA:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonEditMenu.doClick();
        }
    }//GEN-LAST:event_jButtonEditMenuKeyPressed

    private void jTextFieldEditMenuFoodNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEditMenuFoodNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEditMenuFoodNameActionPerformed

    private void jTextFieldEditMenuFoodNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEditMenuFoodNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonEditMenu.doClick();
        }
    }//GEN-LAST:event_jTextFieldEditMenuFoodNameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameEditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameEditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameEditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameEditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEditMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelEditMenu;
    private javax.swing.JButton jButtonEditMenu;
    private javax.swing.JComboBox jComboBoxEditMennuCategory;
    private javax.swing.JLabel jLabeRegisterFullName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRegisterUserName;
    private javax.swing.JLabel jLabelResgisterPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldEditMenuFoodName;
    private javax.swing.JSpinner jTextFieldEditMenuPrice;
    // End of variables declaration//GEN-END:variables
}
