/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DataAccess.Table;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.CallableStatement;
import Database.Connect;

public class JFrameAccountInformation extends javax.swing.JFrame {
    
    public static Connection conn = Connect.getConnect();
    public static PreparedStatement pst = null;
    public static ResultSet rs = null;
    public static CallableStatement cst = null;
    public String fullNameString;
    public String userNameString;
    public String passwordString;

    public JFrameAccountInformation() {
        initComponents();
        this.jTextFieldUserNameInfo.setEditable(false);
        this.jPasswordFieldPasswordInfo.setEditable(false);
        this.jTextFieldFullNameInfo.setEditable(false);
        // Hiển thị thông tin tài khoản đăng nhập
        try {
            pst = conn.prepareStatement("SELECT * FROM quanlyquancafethucan.taikhoandangnhap WHERE ID = ?");
            pst.setInt(1, JFrameLogin.IDAccount);
            rs = pst.executeQuery();
            if (rs.next()) {
                fullNameString = rs.getString("FullName");
                userNameString = rs.getString("UserName");
                passwordString = rs.getString("PassWD");
                jTextFieldFullNameInfo.setText(fullNameString);
                jTextFieldUserNameInfo.setText(userNameString);
                jPasswordFieldPasswordInfo.setText(passwordString);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Lỗi truy xuất dữ liệu", 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelUserNameInfo = new javax.swing.JLabel();
        jTextFieldUserNameInfo = new javax.swing.JTextField();
        jLabelPasswordInfo = new javax.swing.JLabel();
        jLabelNewPassword = new javax.swing.JLabel();
        jLabelRetypeNewPassword = new javax.swing.JLabel();
        jButtonEditAccountInfo = new javax.swing.JButton();
        jPasswordFieldNewPassword = new javax.swing.JPasswordField();
        jPasswordFieldPasswordInfo = new javax.swing.JPasswordField();
        jButtonConfirmAccountInfo = new javax.swing.JButton();
        jTextFieldRetypeNewPassword = new javax.swing.JPasswordField();
        jCheckBoxShowPasswordInfo = new javax.swing.JCheckBox();
        jButtonCancelEditAcountInfo = new javax.swing.JButton();
        jLabelNewUserNameInfo = new javax.swing.JLabel();
        jTextFieldNewLoginNameInfo = new javax.swing.JTextField();
        jTextFieldFullNameInfo = new javax.swing.JTextField();
        jLabelUserNameInfo1 = new javax.swing.JLabel();
        jLabelUserNameInfo2 = new javax.swing.JLabel();
        jLabelNewFullName = new javax.swing.JLabel();
        jTextFieldNewFullName = new javax.swing.JTextField();
        jButtonConfirmAccountInfo1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setTitle("Thông Tin Người Dùng");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thông Tin Tài Khoản");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelUserNameInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUserNameInfo.setText("Tên Đăng nhập:");

        jTextFieldUserNameInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldUserNameInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserNameInfoActionPerformed(evt);
            }
        });

        jLabelPasswordInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPasswordInfo.setText("Mật khẩu:");

        jLabelNewPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNewPassword.setText("Mật khẩu mới:");
        jLabelNewPassword.setEnabled(false);

        jLabelRetypeNewPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRetypeNewPassword.setText("Nhập lại:");
        jLabelRetypeNewPassword.setEnabled(false);

        jButtonEditAccountInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditAccountInfo.setText("Chỉnh sửa");
        jButtonEditAccountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditAccountInfoActionPerformed(evt);
            }
        });

        jPasswordFieldNewPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordFieldNewPassword.setEnabled(false);

        jPasswordFieldPasswordInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jButtonConfirmAccountInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonConfirmAccountInfo.setText("Cập nhật");
        jButtonConfirmAccountInfo.setEnabled(false);
        jButtonConfirmAccountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmAccountInfoActionPerformed(evt);
            }
        });
        jButtonConfirmAccountInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonConfirmAccountInfoKeyPressed(evt);
            }
        });

        jTextFieldRetypeNewPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldRetypeNewPassword.setEnabled(false);
        jTextFieldRetypeNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRetypeNewPasswordActionPerformed(evt);
            }
        });
        jTextFieldRetypeNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRetypeNewPasswordKeyPressed(evt);
            }
        });

        jCheckBoxShowPasswordInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxShowPasswordInfo.setText("Hiển thị");
        jCheckBoxShowPasswordInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxShowPasswordInfoActionPerformed(evt);
            }
        });
        jCheckBoxShowPasswordInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCheckBoxShowPasswordInfoKeyPressed(evt);
            }
        });

        jButtonCancelEditAcountInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelEditAcountInfo.setText("Hủy");
        jButtonCancelEditAcountInfo.setEnabled(false);
        jButtonCancelEditAcountInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelEditAcountInfoActionPerformed(evt);
            }
        });

        jLabelNewUserNameInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNewUserNameInfo.setText("Tên Đăng nhập:");
        jLabelNewUserNameInfo.setEnabled(false);

        jTextFieldNewLoginNameInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNewLoginNameInfo.setEnabled(false);
        jTextFieldNewLoginNameInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNewLoginNameInfoActionPerformed(evt);
            }
        });

        jTextFieldFullNameInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldFullNameInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFullNameInfoActionPerformed(evt);
            }
        });

        jLabelUserNameInfo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabelUserNameInfo2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUserNameInfo2.setText("Họ tên");

        jLabelNewFullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNewFullName.setText("Họ tên:");
        jLabelNewFullName.setEnabled(false);

        jTextFieldNewFullName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldNewFullName.setEnabled(false);
        jTextFieldNewFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNewFullNameActionPerformed(evt);
            }
        });

        jButtonConfirmAccountInfo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonConfirmAccountInfo1.setText("Quay lại");
        jButtonConfirmAccountInfo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmAccountInfo1ActionPerformed(evt);
            }
        });

        jLabel2.setText("*Bạn chỉ có thể chỉnh sửa thông tin cá nhân và tài khoản của mình");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelPasswordInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelUserNameInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelUserNameInfo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelUserNameInfo1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxShowPasswordInfo)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jPasswordFieldPasswordInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                                .addComponent(jTextFieldFullNameInfo)
                                                .addComponent(jTextFieldUserNameInfo))))))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelNewFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelRetypeNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNewUserNameInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelNewPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonConfirmAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNewLoginNameInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(jPasswordFieldNewPassword)
                                    .addComponent(jTextFieldRetypeNewPassword)
                                    .addComponent(jTextFieldNewFullName)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButtonEditAccountInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelEditAcountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConfirmAccountInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFullNameInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUserNameInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUserNameInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUserNameInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPasswordInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldPasswordInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxShowPasswordInfo)
                .addGap(4, 4, 4)
                .addComponent(jLabelUserNameInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirmAccountInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelEditAcountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewFullName)
                    .addComponent(jTextFieldNewFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewUserNameInfo)
                    .addComponent(jTextFieldNewLoginNameInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewPassword)
                    .addComponent(jPasswordFieldNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRetypeNewPassword)
                    .addComponent(jTextFieldRetypeNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConfirmAccountInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditAccountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditAccountInfoActionPerformed
        // Chỉnh sửa mật khẩu mới
        // Enable mục chỉnh sửa
        jButtonEditAccountInfo.setEnabled(false);
        jLabelNewFullName.setEnabled(true);
        jTextFieldNewFullName.setEnabled(true);
        jLabelNewUserNameInfo.setEnabled(true);
        jTextFieldNewLoginNameInfo.setEnabled(true);
        jLabelNewPassword.setEnabled(true);
        jPasswordFieldNewPassword.setEnabled(true);
        jLabelRetypeNewPassword.setEnabled(true);
        jTextFieldRetypeNewPassword.setEnabled(true);
        jButtonConfirmAccountInfo.setEnabled(true);
        jButtonCancelEditAcountInfo.setEnabled(true);
    }//GEN-LAST:event_jButtonEditAccountInfoActionPerformed

    private void jButtonConfirmAccountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmAccountInfoActionPerformed
        // Disable mục chỉnh sửa
        jLabelNewUserNameInfo.setEnabled(false);
        jTextFieldNewLoginNameInfo.setEnabled(false);
        jLabelNewPassword.setEnabled(false);
        jPasswordFieldNewPassword.setEnabled(false);
        jLabelRetypeNewPassword.setEnabled(false);
        jTextFieldRetypeNewPassword.setEnabled(false);
        jButtonConfirmAccountInfo.setEnabled(false);
        jButtonCancelEditAcountInfo.setEnabled(false);
        jLabelNewFullName.setEnabled(false);
        jTextFieldNewFullName.setEnabled(false);
        jButtonEditAccountInfo.setEnabled(true);
        
        // Chỉnh sửa thông tin tài khoản người dùng hiện tại.
        // Kiểm tra có trường nào chưa điền không
        if(jTextFieldNewFullName.getText().length() == 0 || jTextFieldNewLoginNameInfo.getText().length() == 0 || jPasswordFieldNewPassword.getText().length() == 0 || jTextFieldRetypeNewPassword.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập đủ thông tin", "Nhập thiếu thông tin", 2);
        }
        // Kiểm tra khớp mật khẩu
        else if(!(this.jPasswordFieldNewPassword.getText().equals(this.jTextFieldRetypeNewPassword.getText()))){
            JOptionPane.showMessageDialog(null, "Bạn phải nhập mật khẩu trùng khớp nhau", "Thông báo", 2);
        }
        else {
            try {
            cst = conn.prepareCall("{CALL CapNhatTaiKhoan(?, ?, ?, ?)}");
            cst.setString(1, userNameString);                           // Tên đăng nhập cũ
            cst.setString(2, jTextFieldNewLoginNameInfo.getText());     // Tên đăng nhập mới (Nếu có)
            cst.setString(3, jPasswordFieldNewPassword.getText());      // Mật khẩu mới (Nếu có)
            cst.setString(4, jTextFieldNewFullName.getText());          // Họ tên mới (Nếu có)
            cst.executeQuery();
            JOptionPane.showMessageDialog(null, "Chỉnh sửa thông tin thành công!", "Thành công.", 1);
            //Cập nhật Main:
            JFrameLogin.MainGUI.jLabelCurrentUserName.setText("<html>" + "Người dùng: " + jTextFieldNewFullName.getText() + "<br>Tên đăng nhập: " + jTextFieldNewLoginNameInfo.getText() + "</html>");
            jTextFieldUserNameInfo.setText(jTextFieldNewLoginNameInfo.getText());
            jPasswordFieldPasswordInfo.setText(jPasswordFieldNewPassword.getText());
            jTextFieldFullNameInfo.setText(jTextFieldNewFullName.getText());
            // Hoàn thành Chỉnh sửa, Reset Textfields
            jTextFieldNewFullName.setText(null);
            jTextFieldNewLoginNameInfo.setText(null);
            jPasswordFieldNewPassword.setText(null);
            jTextFieldRetypeNewPassword.setText(null);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Chỉnh sửa không thành công!", "Thất bại.", 2);
            }
        }
    }//GEN-LAST:event_jButtonConfirmAccountInfoActionPerformed

    private void jTextFieldUserNameInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserNameInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserNameInfoActionPerformed

    private void jCheckBoxShowPasswordInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxShowPasswordInfoActionPerformed
        //Chọn để hiển thị mật khẩu, bỏ chọn để giấu mật khẩu
        if(jCheckBoxShowPasswordInfo.isSelected()) {
            jPasswordFieldPasswordInfo.setEchoChar((char)0);
        }
        else {
            jPasswordFieldPasswordInfo.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPasswordInfoActionPerformed

    private void jCheckBoxShowPasswordInfoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCheckBoxShowPasswordInfoKeyPressed
        // Nhấn Enter để hiển thị password
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jCheckBoxShowPasswordInfo.doClick();
        }
    }//GEN-LAST:event_jCheckBoxShowPasswordInfoKeyPressed

    private void jButtonCancelEditAcountInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelEditAcountInfoActionPerformed
        // Khi nhấn vào hủy chỉnh sửa mật khẩu
        jLabelNewUserNameInfo.setEnabled(false);
        jTextFieldNewLoginNameInfo.setEnabled(false);
        jLabelNewPassword.setEnabled(false);
        jPasswordFieldNewPassword.setEnabled(false);
        jLabelRetypeNewPassword.setEnabled(false);
        jTextFieldRetypeNewPassword.setEnabled(false);
        jButtonConfirmAccountInfo.setEnabled(false);
        jButtonCancelEditAcountInfo.setEnabled(false);
        jLabelNewFullName.setEnabled(false);
        jTextFieldNewFullName.setEnabled(false);
        jButtonEditAccountInfo.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelEditAcountInfoActionPerformed

    private void jTextFieldNewLoginNameInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNewLoginNameInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNewLoginNameInfoActionPerformed

    private void jTextFieldFullNameInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFullNameInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFullNameInfoActionPerformed

    private void jTextFieldRetypeNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRetypeNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRetypeNewPasswordActionPerformed

    private void jTextFieldNewFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNewFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNewFullNameActionPerformed

    private void jTextFieldRetypeNewPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRetypeNewPasswordKeyPressed
        // Nhấn ENTER để xác nhận:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            this.jButtonConfirmAccountInfo.doClick();
        }
    }//GEN-LAST:event_jTextFieldRetypeNewPasswordKeyPressed

    private void jButtonConfirmAccountInfoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonConfirmAccountInfoKeyPressed
        // Nhấn ENTER để xác nhận:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            this.jButtonConfirmAccountInfo.doClick();
        }
    }//GEN-LAST:event_jButtonConfirmAccountInfoKeyPressed

    private void jButtonConfirmAccountInfo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmAccountInfo1ActionPerformed
        // Quit:
        // Cập nhật cho bảng danh sách tài khoản:
        if(JFrameMain.Admin.isActive())Table.LoadDataTable("SELECT ID AS 'STT', UserName AS 'Tên đăng nhập', FullName AS 'Họ và tên' FROM quanlyquancafethucan.taikhoandangnhap ORDER BY ID ASC", JFrameMain.Admin.jTableAccount);
        this.dispose();
    }//GEN-LAST:event_jButtonConfirmAccountInfo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAccountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAccountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAccountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAccountInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAccountInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelEditAcountInfo;
    private javax.swing.JButton jButtonConfirmAccountInfo;
    private javax.swing.JButton jButtonConfirmAccountInfo1;
    private javax.swing.JButton jButtonEditAccountInfo;
    private javax.swing.JCheckBox jCheckBoxShowPasswordInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNewFullName;
    private javax.swing.JLabel jLabelNewPassword;
    private javax.swing.JLabel jLabelNewUserNameInfo;
    private javax.swing.JLabel jLabelPasswordInfo;
    private javax.swing.JLabel jLabelRetypeNewPassword;
    private javax.swing.JLabel jLabelUserNameInfo;
    private javax.swing.JLabel jLabelUserNameInfo1;
    private javax.swing.JLabel jLabelUserNameInfo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldNewPassword;
    private javax.swing.JPasswordField jPasswordFieldPasswordInfo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldFullNameInfo;
    private javax.swing.JTextField jTextFieldNewFullName;
    private javax.swing.JTextField jTextFieldNewLoginNameInfo;
    private javax.swing.JPasswordField jTextFieldRetypeNewPassword;
    private javax.swing.JTextField jTextFieldUserNameInfo;
    // End of variables declaration//GEN-END:variables
}
