/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import Database.Connect;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import DataAccess.Table;
import DataAccess.ComboBox;

public class JFrameAddMenu extends javax.swing.JFrame {

    public static Connection conn = Connect.getConnect();
    public static PreparedStatement pst = null;
    public static CallableStatement cst = null;
    public static ResultSet rs = null;
            
    public JFrameAddMenu() {
        initComponents();
        ComboBox.LoadDataComboBox("SELECT * FROM quanlyquancafethucan.PhanLoaiMenu", jComboBoxAddMenuCategory, "Ten");
        jSpinnerAddMenuID.setValue(getMenuRowCount() + 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabeRegisterFullName = new javax.swing.JLabel();
        jLabelResgisterPassword = new javax.swing.JLabel();
        jLabelRegisterUserName = new javax.swing.JLabel();
        jButtonAddMenu = new javax.swing.JButton();
        jButtonCancelAddMenu = new javax.swing.JButton();
        jTextFieldAddMenuFoodName = new javax.swing.JTextField();
        jSpinnerAddMenuPrice = new javax.swing.JSpinner();
        jComboBoxAddMenuCategory = new javax.swing.JComboBox();
        jLabeRegisterFullName1 = new javax.swing.JLabel();
        jSpinnerAddMenuID = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm món mới Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jLabeRegisterFullName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeRegisterFullName.setText("Tên món:");

        jLabelResgisterPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelResgisterPassword.setText("Giá:");

        jLabelRegisterUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRegisterUserName.setText("Phân loại:");

        jButtonAddMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddMenu.setText("Thêm");
        jButtonAddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddMenuActionPerformed(evt);
            }
        });
        jButtonAddMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAddMenuKeyPressed(evt);
            }
        });

        jButtonCancelAddMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancelAddMenu.setText("Quay lại");
        jButtonCancelAddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelAddMenuActionPerformed(evt);
            }
        });
        jButtonCancelAddMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonCancelAddMenuKeyPressed(evt);
            }
        });

        jTextFieldAddMenuFoodName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jSpinnerAddMenuPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinnerAddMenuPrice.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), null, null, Double.valueOf(1000.0d)));

        jComboBoxAddMenuCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabeRegisterFullName1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabeRegisterFullName1.setText("Mã món:");

        jSpinnerAddMenuID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinnerAddMenuID.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelRegisterUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(jLabeRegisterFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelResgisterPassword))
                            .addComponent(jLabeRegisterFullName1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxAddMenuCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerAddMenuPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jSpinnerAddMenuID, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jTextFieldAddMenuFoodName)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jButtonAddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelAddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldAddMenuFoodName)
                    .addComponent(jLabeRegisterFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeRegisterFullName1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerAddMenuID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegisterUserName)
                    .addComponent(jComboBoxAddMenuCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResgisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerAddMenuPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelAddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelAddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelAddMenuActionPerformed
        // QUAY LẠI
        dispose();
    }//GEN-LAST:event_jButtonCancelAddMenuActionPerformed

    private void jButtonAddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMenuActionPerformed
        // BUTTION Đăng ký tài khoản đăng nhập mới.
        // Kiểm tra món đã tồn tại chưa:
        boolean isExist = false;
        try {
            pst = conn.prepareStatement("SELECT * FROM quanlyquancafethucan.menu WHERE TenMon = ?");
            pst.setString(1, jTextFieldAddMenuFoodName.getText());
            rs = pst.executeQuery();
            if(rs.next()) {
                JOptionPane.showMessageDialog(null, "Món này hiện đã tồn tại!", "Món đã tồn tại.", 2);
                isExist = true;     // Đã tồn tại.
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "JFrameAddMenu.", 2);
        }
        // Nếu chưa thì thực hiện thêm món vào:
        if(isExist == false) {
            try {
                cst = conn.prepareCall("{CALL ThemMenu(?, ?, ?, ?, ?)}");
                cst.setInt(1, (int) jSpinnerAddMenuID.getValue());
                if(jComboBoxAddMenuCategory.getSelectedItem().toString().equals("Nước uống")) {
                    cst.setInt(2, 1);   // ID Phân loại. 1 || 2 || 3
                }
                else if(jComboBoxAddMenuCategory.getSelectedItem().toString().equals("Thức ăn")) {
                    cst.setInt(2, 2);   // ID Phân loại. 1 || 2 || 3
                }
                else cst.setInt(2, 3);  // ID Phân loại. 1 || 2 || 3
                cst.setString(3, jTextFieldAddMenuFoodName.getText());          // Tên món
                cst.setString(4, jComboBoxAddMenuCategory.getSelectedItem().toString());          // Phân loại Thức ăn || Nước uống || Khác
                cst.setDouble(5, (double) jSpinnerAddMenuPrice.getValue());   // Giá
                cst.executeQuery();
                Table.LoadDataTable("SELECT ID AS 'Mã món', TenMon AS 'Tên món', PhanLoai AS 'Phân loại', Gia AS 'Giá bán' FROM quanlyquancafethucan.menu ORDER BY ID ASC", JFrameMain.Admin.jTableMenu);
                JOptionPane.showMessageDialog(null, "Đã thêm " + jTextFieldAddMenuFoodName.getText() + " vào Menu!", "Thêm món.", 1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Mã Món không được trùng nhau!", "Thông báo lỗi.", 2);
            }
        }
    }//GEN-LAST:event_jButtonAddMenuActionPerformed
    
    private void jButtonCancelAddMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonCancelAddMenuKeyPressed
        // Nhấn ENTER Nút Thoát == Nhấn buttion
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonCancelAddMenu.doClick();
        }
    }//GEN-LAST:event_jButtonCancelAddMenuKeyPressed

    private void jButtonAddMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAddMenuKeyPressed
        // NHẤN ENTER == CLICK:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER) {
            jButtonAddMenu.doClick();
        }
    }//GEN-LAST:event_jButtonAddMenuKeyPressed

    private int getMenuRowCount() {
        int menuRowCount = 0;
        try {
            pst = conn.prepareStatement("SELECT * FROM menu");
            rs = pst.executeQuery();
            while (rs.next()) menuRowCount = rs.getRow();
        } catch (Exception e) {
        }
        return menuRowCount;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAddMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddMenu;
    private javax.swing.JButton jButtonCancelAddMenu;
    private javax.swing.JComboBox jComboBoxAddMenuCategory;
    private javax.swing.JLabel jLabeRegisterFullName;
    private javax.swing.JLabel jLabeRegisterFullName1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelRegisterUserName;
    private javax.swing.JLabel jLabelResgisterPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinnerAddMenuID;
    private javax.swing.JSpinner jSpinnerAddMenuPrice;
    private javax.swing.JTextField jTextFieldAddMenuFoodName;
    // End of variables declaration//GEN-END:variables
}
