
package GUI;

import java.util.Date;
import javax.swing.JOptionPane;
import DataAccess.Table;
import DataAccess.ComboBox;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Database.Connect;
import java.text.SimpleDateFormat;

public final class JFrameAdmin extends javax.swing.JFrame {

    public static int IDMenu; // Biến tạm cho việc thêm sửa xóa MENU
    public static Connection conn = Connect.getConnect();
    public static PreparedStatement pst = null;
    public static PreparedStatement pst1 = null;
    public static PreparedStatement pst2 = null;
    public static ResultSet rs = null;
    public String dateCheckIn;
    public String dateCheckOut;
    
    public JFrameAdmin() {
        initComponents();
        
        // CODE TAB "DOANH THU":
        //String today = new Date().toString();
        jDateCheckIn.setDate(new Date());
        jDateCheckOut.setDate(new Date());
        SimpleDateFormat cin = new SimpleDateFormat("yyyy-MM-dd");
        dateCheckIn = cin.format(jDateCheckIn.getDate());
        SimpleDateFormat cout = new SimpleDateFormat("yyyy-MM-dd");
        dateCheckOut = cout.format(jDateCheckOut.getDate());
        //Table.LoadDataTable("SELECT ID AS 'STT', TenMon AS 'Tên món', SoLuong AS 'Số lượng', DonGia AS 'Đơn giá', ThanhTien AS 'Thành tiền', Ngay AS 'Ngày thanh toán' FROM doanhthu WHERE Ngay < " + dateCheckIn + " AND Ngay > " + dateCheckOut, jTableRevenue);
        Table.LoadDataTable("SELECT ID AS 'STT', TenMon AS 'Tên món', SoLuong AS 'Số lượng', DonGia AS 'Đơn giá', ThanhTien AS 'Thành tiền', Ngay AS 'Ngày thanh toán'" +
            "FROM doanhthu WHERE Ngay >= '" + dateCheckIn + "' AND Ngay <= '" + dateCheckOut + "'", jTableRevenue);
        setValueTotalRevenue();
        
        
        // CODE TAB "MENU":
        String sqlComboBoxCategory = "SELECT * FROM quanlyquancafethucan.PhanLoaiMenu";
        ComboBox.LoadDataComboBox(sqlComboBoxCategory, jComboBoxMenuFoodCategory, "Ten");
        
        String sqlTableMenu = "SELECT ID AS 'Mã món', TenMon AS 'Tên món', PhanLoai AS 'Phân loại', Gia AS 'Giá bán' FROM quanlyquancafethucan.menu ORDER BY ID ASC";
        Table.LoadDataTable(sqlTableMenu, jTableMenu);
        
        
        // CODE TAB "BÀN PHỤC VỤ":
        jComboBoxTableFoodStatus.addItem("Trống");
        jComboBoxTableFoodStatus.addItem("Có người");
        String sqlTableFood = "SELECT ID AS 'Mã bàn', TenBan AS 'Tên Bàn', TrangThai AS 'Trạng Thái' FROM quanlyquancafethucan.BanPhucVu ORDER BY ID ASC";
        Table.LoadDataTable(sqlTableFood, jTableTableFood);
        
        // CODE TAB "TÀI KHOẢN":
        String sqlTableAccount = "SELECT ID AS 'STT', UserName AS 'Tên Đăng Nhập', FullName AS 'Họ Và Tên' FROM quanlyquancafethucan.taikhoandangnhap ORDER BY ID ASC";
        Table.LoadDataTable(sqlTableAccount, jTableAccount);
        jTextFieldAccountUserName.setText(jTableAccount.getValueAt(0, 1).toString());
        jTextFieldAccountFullName.setText(jTableAccount.getValueAt(0, 2).toString());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelTable = new javax.swing.JPanel();
        jButtonTableAdd = new javax.swing.JButton();
        jButtonTableDelete = new javax.swing.JButton();
        jButtonTableEdit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTableFood = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTableFoodName = new javax.swing.JTextField();
        jComboBoxTableFoodStatus = new javax.swing.JComboBox();
        jSpinnerTableFoodID = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        jButtonMenuAdd = new javax.swing.JButton();
        jButtonMenuDelete = new javax.swing.JButton();
        jButtonMenuEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMenu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMenuID = new javax.swing.JTextField();
        jTextFieldMenuFoodName = new javax.swing.JTextField();
        jComboBoxMenuFoodCategory = new javax.swing.JComboBox();
        jSpinnerMenuPrice = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelAccount = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonAccountAdd = new javax.swing.JButton();
        jButtonAccountEdit = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableAccount = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldAccountUserName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldAccountFullName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jDateCheckIn = new com.toedter.calendar.JDateChooser();
        jDateCheckOut = new com.toedter.calendar.JDateChooser();
        jLabelDateCheckIn = new javax.swing.JLabel();
        jLabelDateCheckIn1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableRevenue = new javax.swing.JTable();
        jButtonShowRevenue = new javax.swing.JButton();
        jSpinnerRevenue = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản Trị");
        setUndecorated(true);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButtonTableAdd.setBackground(new java.awt.Color(0, 255, 0));
        jButtonTableAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonTableAdd.setForeground(new java.awt.Color(0, 0, 204));
        jButtonTableAdd.setText("Thêm");
        jButtonTableAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTableAddActionPerformed(evt);
            }
        });

        jButtonTableDelete.setBackground(new java.awt.Color(204, 0, 0));
        jButtonTableDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonTableDelete.setForeground(new java.awt.Color(255, 204, 0));
        jButtonTableDelete.setText("Xóa");
        jButtonTableDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTableDeleteActionPerformed(evt);
            }
        });

        jButtonTableEdit.setBackground(new java.awt.Color(255, 255, 0));
        jButtonTableEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonTableEdit.setForeground(new java.awt.Color(0, 0, 255));
        jButtonTableEdit.setText("Sửa");
        jButtonTableEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTableEditActionPerformed(evt);
            }
        });

        jTableTableFood.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableTableFood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableTableFood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTableFoodMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableTableFood);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ID:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tên bàn:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Trạng thái:");

        jTextFieldTableFoodName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldTableFoodName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTableFoodNameActionPerformed(evt);
            }
        });

        jComboBoxTableFoodStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jSpinnerTableFoodID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinnerTableFoodID.setModel(new javax.swing.SpinnerNumberModel());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Danh sách bàn và trạng thái bàn");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 102));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Thông tin chi tiết bàn");

        javax.swing.GroupLayout jPanelTableLayout = new javax.swing.GroupLayout(jPanelTable);
        jPanelTable.setLayout(jPanelTableLayout);
        jPanelTableLayout.setHorizontalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTableLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanelTableLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelTableLayout.createSequentialGroup()
                                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jSpinnerTableFoodID, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTableFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxTableFoodStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelTableLayout.createSequentialGroup()
                                .addComponent(jButtonTableAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTableEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTableDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelTableLayout.setVerticalGroup(
            jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(jPanelTableLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel20))
                .addGap(53, 53, 53)
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerTableFoodID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldTableFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxTableFoodStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTableEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTableDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTableAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("BÀN PHỤC VỤ", jPanelTable);

        jButtonMenuAdd.setBackground(new java.awt.Color(0, 255, 0));
        jButtonMenuAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonMenuAdd.setForeground(new java.awt.Color(0, 0, 204));
        jButtonMenuAdd.setText("Thêm");
        jButtonMenuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuAddActionPerformed(evt);
            }
        });

        jButtonMenuDelete.setBackground(new java.awt.Color(204, 0, 0));
        jButtonMenuDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonMenuDelete.setForeground(new java.awt.Color(255, 255, 0));
        jButtonMenuDelete.setText("Xóa");
        jButtonMenuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuDeleteActionPerformed(evt);
            }
        });

        jButtonMenuEdit.setBackground(new java.awt.Color(255, 255, 0));
        jButtonMenuEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonMenuEdit.setText("Sửa");
        jButtonMenuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenuEditActionPerformed(evt);
            }
        });

        jTableMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableMenu);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tên món:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Giá bán:");

        jTextFieldMenuID.setEditable(false);
        jTextFieldMenuID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldMenuID.setText("1");

        jTextFieldMenuFoodName.setEditable(false);
        jTextFieldMenuFoodName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldMenuFoodName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMenuFoodNameActionPerformed(evt);
            }
        });

        jComboBoxMenuFoodCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jSpinnerMenuPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSpinnerMenuPrice.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), null, null, Integer.valueOf(1000)));
        jSpinnerMenuPrice.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerMenuPrice, ""));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Thông tin chi tiết món");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 153, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Danh sách món ăn, thức uống");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Phân loại:");

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(24, 24, 24)
                        .addComponent(jComboBoxMenuFoodCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMenuFoodName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMenuID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerMenuPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                                .addComponent(jButtonMenuAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMenuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonMenuDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21))
                .addGap(27, 27, 27)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMenuID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMenuFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxMenuFoodCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerMenuPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonMenuAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMenuEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMenuDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MENU", jPanelMenu);

        jButtonAccountAdd.setBackground(new java.awt.Color(0, 255, 0));
        jButtonAccountAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAccountAdd.setForeground(new java.awt.Color(0, 0, 204));
        jButtonAccountAdd.setText("Thêm");
        jButtonAccountAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccountAddActionPerformed(evt);
            }
        });

        jButtonAccountEdit.setBackground(new java.awt.Color(255, 255, 0));
        jButtonAccountEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAccountEdit.setText("Sửa");
        jButtonAccountEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccountEditActionPerformed(evt);
            }
        });

        jTableAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAccountMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableAccount);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Tên đăng nhập:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Họ và tên");

        jTextFieldAccountUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAccountUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccountUserNameActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Danh sách tài khoản đăng nhập");

        jTextFieldAccountFullName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldAccountFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccountFullNameActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 102));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Thông tin cơ bản");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAccountFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldAccountUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jButtonAccountAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAccountEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAccountUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAccountFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAccountAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAccountEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelAccountLayout = new javax.swing.GroupLayout(jPanelAccount);
        jPanelAccount.setLayout(jPanelAccountLayout);
        jPanelAccountLayout.setHorizontalGroup(
            jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
            .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAccountLayout.createSequentialGroup()
                    .addGap(0, 2, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 3, Short.MAX_VALUE)))
        );
        jPanelAccountLayout.setVerticalGroup(
            jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
            .addGroup(jPanelAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAccountLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("TÀI KHOẢN", jPanelAccount);

        jDateCheckIn.setDateFormatString("dd/MM/yyyy");
        jDateCheckIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jDateCheckOut.setDateFormatString("dd/MM/yyyy");
        jDateCheckOut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelDateCheckIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDateCheckIn.setForeground(new java.awt.Color(0, 0, 153));
        jLabelDateCheckIn.setText("Từ ngày");

        jLabelDateCheckIn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDateCheckIn1.setForeground(new java.awt.Color(0, 0, 153));
        jLabelDateCheckIn1.setText("Đến ngày");

        jTableRevenue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableRevenue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTableRevenue);

        jButtonShowRevenue.setBackground(new java.awt.Color(51, 255, 51));
        jButtonShowRevenue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonShowRevenue.setForeground(new java.awt.Color(0, 0, 255));
        jButtonShowRevenue.setText("Xem");
        jButtonShowRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowRevenueActionPerformed(evt);
            }
        });

        jSpinnerRevenue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonShowRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabelDateCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                        .addComponent(jLabelDateCheckIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jDateCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDateCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jLabelDateCheckIn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonShowRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("DOANH THU", jPanel1);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("QUẢN TRỊ");

        jButtonBack.setBackground(new java.awt.Color(255, 102, 0));
        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(51, 0, 204));
        jButtonBack.setText("Quay lại");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(846, 846, 846)
                .addComponent(jButtonBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        JFrameLogin.MainGUI.jComboBoxFoodCategory.setSelectedItem("Khác");
        JFrameLogin.MainGUI.jComboBoxFoodCategory.setSelectedItem("Tất cả");
        JFrameLogin.MainGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonShowRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowRevenueActionPerformed
        // TODO add your handling code here:
        jTableRevenue.removeAll();
        SimpleDateFormat dateIn = new SimpleDateFormat("yyyy-MM-dd");
        dateCheckIn = dateIn.format(jDateCheckIn.getDate());
        SimpleDateFormat dateOut = new SimpleDateFormat("yyyy-MM-dd");
        dateCheckOut = dateIn.format(jDateCheckOut.getDate());
        Table.LoadDataTable("SELECT ID AS 'STT', TenMon AS 'Tên món', SoLuong AS 'Số lượng', DonGia AS 'Đơn giá', ThanhTien AS 'Thành tiền', Ngay AS 'Ngày thanh toán'" +
            "FROM doanhthu WHERE Ngay >= '" + dateCheckIn + "' AND Ngay <= '" + dateCheckOut + "'", jTableRevenue);
        setValueTotalRevenue();
    }//GEN-LAST:event_jButtonShowRevenueActionPerformed

    private void jTextFieldAccountFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccountFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountFullNameActionPerformed

    private void jTextFieldAccountUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccountUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccountUserNameActionPerformed

    private void jTableAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAccountMouseClicked
        // NHẤP VÀO DÒNG TRONG BẢNG CỦA TAB TÀI KHOẢN:
        try {
            // Lấy chỉ số dòng đang click:
            int rowIndexAccount = jTableAccount.getSelectedRow();
            // Lấy thông tin cột đầu tiên của dòng đang click:
            String IDRowAccount = this.jTableAccount.getModel().getValueAt(rowIndexAccount, 0).toString();
            String sqlSelectedRowAccount = "SELECT * FROM quanlyquancafethucan.taikhoandangnhap WHERE ID = '"+IDRowAccount+"'";
            ResultSet rs = Table.FillTextField(sqlSelectedRowAccount);
            if(rs.next()) {
                this.jTextFieldAccountUserName.setText(rs.getString("UserName"));
                this.jTextFieldAccountFullName.setText(rs.getString("FullName"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "JFrameAdminTabAccount", 1);
        }
    }//GEN-LAST:event_jTableAccountMouseClicked

    private void jButtonAccountEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccountEditActionPerformed
        // XEM,SỬA THÔNG TIN TÀI KHOẢN:
        JFrameAccountInformation JFEditAccout = new JFrameAccountInformation();
        JFEditAccout.setVisible(true);
    }//GEN-LAST:event_jButtonAccountEditActionPerformed

    private void jButtonAccountAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccountAddActionPerformed
        // THÊM TÀI KHOẢN TRONG TAB "TÀI KHOẢN":
        JFrameAddAccount JFAdd = new JFrameAddAccount();
        JFAdd.setVisible(true);
    }//GEN-LAST:event_jButtonAccountAddActionPerformed

    private void jTextFieldMenuFoodNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMenuFoodNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMenuFoodNameActionPerformed

    private void jTableMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMenuMouseClicked
        // NHẤP VÀO DÒNG TRONG BẢNG CỦA TAB MENU:
        try {
            // Số thứ tự dòng trong bảng hiện đang được chọn (bắt đầu từ 0 đếm lên):
            int rowIndexMenu = this.jTableMenu.getSelectedRow();
            // Lấy giá trị dòng vừa chọn ở cột đầu tiên (0):
            String IDRowMenu = this.jTableMenu.getModel().getValueAt(rowIndexMenu, 0).toString();
            String sqlSelectedRowMenu = "SELECT * FROM quanlyquancafethucan.menu WHERE ID ='" + IDRowMenu + "'";
            ResultSet rs = Table.FillTextField(sqlSelectedRowMenu);
            if(rs.next()) {
                IDMenu = rs.getInt("ID");
                jTextFieldMenuID.setText(rs.getString("ID"));
                jTextFieldMenuFoodName.setText(rs.getString("TenMon"));
                jComboBoxMenuFoodCategory.setSelectedItem(rs.getString("PhanLoai"));
                jSpinnerMenuPrice.setValue(rs.getDouble("Gia"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "JFrameAdminTabMenu", 1);
        }
    }//GEN-LAST:event_jTableMenuMouseClicked

    private void jButtonMenuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuEditActionPerformed
        // CHỈNH SỬA LẠI 1 DÒNG TRONG MENU:
        JFrameEditMenu EditMenu = new JFrameEditMenu();
        EditMenu.setVisible(true);
    }//GEN-LAST:event_jButtonMenuEditActionPerformed

    private void jButtonMenuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuDeleteActionPerformed
        // XÓA MENU:
        try {
            //pst = conn.prepareStatement("DELETE FROM hoadonchitiet WHERE IDMenu = ?");
            pst1 = conn.prepareStatement("DELETE FROM menu WHERE ID = ?");
            //pst.setInt(1, IDMenu);
            pst1.setInt(1, Integer.parseInt(jTextFieldMenuID.getText()));
            //System.out.println(Integer.parseInt(jTextFieldMenuID.getText()));
            if(JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa " + jTextFieldMenuFoodName.getText() + "?", "Xác nhận xóa.", 0) == 0) {
                //pst.executeUpdate();
                pst1.executeUpdate();
                JOptionPane.showMessageDialog(null, "Đã xóa " + jTextFieldMenuFoodName.getText() + " ra khỏi menu.", "Xóa món thành công", 1);
                jTextFieldMenuID.setText(null);
                jTextFieldMenuFoodName.setText(null);
                jComboBoxMenuFoodCategory.setSelectedItem(null);
                jSpinnerMenuPrice.setValue(0);
                Table.LoadDataTable("SELECT ID AS 'ID', TenMon AS 'Tên món', PhanLoai AS 'Phân loại', Gia AS 'Giá bán' FROM quanlyquancafethucan.menu ORDER BY ID ASC", jTableMenu);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Không thể xóa!\nMón này đang có trong hóa đơn thanh toán!", "JFrameAdmin.", 1);
        }
    }//GEN-LAST:event_jButtonMenuDeleteActionPerformed

    private void jButtonMenuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenuAddActionPerformed
        // NÚT THÊM TRONG TAB MENU:
        JFrameAddMenu AddMenu = new JFrameAddMenu();
        AddMenu.setVisible(true);
    }//GEN-LAST:event_jButtonMenuAddActionPerformed

    private void jTextFieldTableFoodNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTableFoodNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTableFoodNameActionPerformed

    private void jTableTableFoodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTableFoodMouseClicked
        // TODO add your handling code here:
        try {
            // Lấy chỉ số dòng đang click:
            int rowIndexAccount = jTableTableFood.getSelectedRow();
            // Lấy thông tin cột đầu tiên của dòng đang click:
            String IDRowAccount = jTableTableFood.getModel().getValueAt(rowIndexAccount, 0).toString();
            String sqlSelectedRowAccount = "SELECT * FROM quanlyquancafethucan.banphucvu WHERE ID = '" +IDRowAccount+ "'";
            ResultSet rs = Table.FillTextField(sqlSelectedRowAccount);
            if(rs.next()) {
                jSpinnerTableFoodID.setValue(rs.getInt("ID"));
                jTextFieldTableFoodName.setText(rs.getString("TenBan"));
                jComboBoxTableFoodStatus.setSelectedItem(rs.getString("TrangThai"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, null, 1);
        }
    }//GEN-LAST:event_jTableTableFoodMouseClicked

    private void jButtonTableEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTableEditActionPerformed
        // TODO add your handling code here:
        JFrameEditTableFood EditTableFood = new JFrameEditTableFood();
        EditTableFood.setVisible(true);
    }//GEN-LAST:event_jButtonTableEditActionPerformed

    private void jButtonTableDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTableDeleteActionPerformed
        // Xóa bàn đang chọn:
        try {
            String s1 = "DELETE FROM hoadon WHERE ID=? AND TinhTrangThanhToan = 1";
            String s2 = "DELETE FROM banphucvu WHERE ID = ? AND TrangThai='Trống'";
            pst = conn.prepareStatement(s1);
            pst1 = conn.prepareStatement(s2);
            pst.setInt(1, (int) jSpinnerTableFoodID.getValue());
            pst1.setInt(1, (int) jSpinnerTableFoodID.getValue());
            if(JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn xóa " + jTextFieldTableFoodName.getText() + "?", "Xác nhận xóa.", 0) == 0) {
                pst.executeUpdate();
                pst1.executeUpdate();

                pst2 = conn.prepareStatement("SELECT * FROM banphucvu WHERE ID = " + (int) jSpinnerTableFoodID.getValue() + " AND TrangThai = 'Có người'");
                rs = pst2.executeQuery();

                if(rs.next()) JOptionPane.showMessageDialog(null, "Không thể xóa vì bàn có hóa đơn chưa xử lý!", "JFrameAdminDeleteTabelFood", 1);
                else JOptionPane.showMessageDialog(null, "Đã xóa " + jTextFieldTableFoodName.getText() + " ra khỏi danh sách.", "Xóa thành công", 1);

                Table.LoadDataTable("SELECT ID AS 'Mã bàn', TenBan AS 'Tên Bàn', TrangThai AS 'Trạng Thái' FROM quanlyquancafethucan.BanPhucVu ORDER BY ID ASC", jTableTableFood);
                JFrameLogin.MainGUI.resetTable();
                JFrameLogin.MainGUI.addTableButton();

                jSpinnerTableFoodID.setValue(0);
                jTextFieldTableFoodName.setText(null);
                jComboBoxTableFoodStatus.setSelectedItem(null);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Không thể xóa vì bàn có hóa đơn chưa xử lý!", "JFrameAdminDeleteTabelFood", 1);
        }
    }//GEN-LAST:event_jButtonTableDeleteActionPerformed

    private void jButtonTableAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTableAddActionPerformed
        // TODO add your handling code here:
        JFrameAddTableFood AddTable = new JFrameAddTableFood();
        AddTable.setVisible(true);
    }//GEN-LAST:event_jButtonTableAddActionPerformed

    
    public void setValueTotalRevenue () {
        double totalRevenue = 0;
        for(int i = 0; i < jTableRevenue.getRowCount(); i++) {
            
            totalRevenue = totalRevenue + (double) jTableRevenue.getValueAt(i, 4);
        }
        jSpinnerRevenue.setValue(totalRevenue);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccountAdd;
    private javax.swing.JButton jButtonAccountEdit;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonMenuAdd;
    private javax.swing.JButton jButtonMenuDelete;
    private javax.swing.JButton jButtonMenuEdit;
    public javax.swing.JButton jButtonShowRevenue;
    private javax.swing.JButton jButtonTableAdd;
    private javax.swing.JButton jButtonTableDelete;
    private javax.swing.JButton jButtonTableEdit;
    public javax.swing.JComboBox jComboBoxMenuFoodCategory;
    public javax.swing.JComboBox jComboBoxTableFoodStatus;
    private com.toedter.calendar.JDateChooser jDateCheckIn;
    private com.toedter.calendar.JDateChooser jDateCheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDateCheckIn;
    private javax.swing.JLabel jLabelDateCheckIn1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelAccount;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JSpinner jSpinnerMenuPrice;
    private javax.swing.JSpinner jSpinnerRevenue;
    public javax.swing.JSpinner jSpinnerTableFoodID;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTableAccount;
    public javax.swing.JTable jTableMenu;
    private javax.swing.JTable jTableRevenue;
    public javax.swing.JTable jTableTableFood;
    private javax.swing.JTextField jTextFieldAccountFullName;
    private javax.swing.JTextField jTextFieldAccountUserName;
    public javax.swing.JTextField jTextFieldMenuFoodName;
    public javax.swing.JTextField jTextFieldMenuID;
    public javax.swing.JTextField jTextFieldTableFoodName;
    // End of variables declaration//GEN-END:variables
}
